# Generated by Django 5.0.7 on 2024-07-29 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_publicacion',
            new_name='fecha_donacion',
        ),
        migrations.AddField(
            model_name='libro',
            name='condicion',
            field=models.CharField(choices=[('mala', 'Mala'), ('buena', 'Buena'), ('excelente', 'Excelente')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='nombre_donante',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
