# Generated by Django 5.0.7 on 2024-08-10 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_prestatario_password_prestatario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestatario',
            name='user',
        ),
    ]
